name: bot-discord

services:
  bot-discord:
    image: ./Dockerfile
    container_name: bot-discord
    restart: always
    env_file: .env
    networks:
      - internal-net
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - internal-net
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db

  redis:
    image: redis
    container_name: redis
    restart: always
    networks:
      - internal-net
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data

networks:
  internal-net:
    driver: bridge